### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by joe-harter** [ArcBees/teamcity-plugins#31]
in the middle of the day the pull request tester stopped triggering. TeamCity bubbles up this error:
java.lang.NumberFormatException: For input string: "2015-10-01T19:41:51.215215+00:00" 

I rebooted TeamCity then installed the latest plugin but I'm getting the exact same error with the same input string. Any suggestions?

Here is the full stacktrace:
jetbrains.buildServer.buildTriggers.BuildTriggerException: java.lang.NumberFormatException: For input string: "2015-10-01T19:41:51.215215+00:00" 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:27) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1100(BuildTriggersChecker.java:80) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:20)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:87) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java:1) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:49)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:48) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: com.google.gson.JsonParseException: java.lang.NumberFormatException: For input string: "2015-10-01T19:41:51.215215+00:00" 
at com.arcbees.vcs.util.GsonDateTypeAdapter.deserialize(GsonDateTypeAdapter.java:63) 
at com.arcbees.vcs.util.GsonDateTypeAdapter.deserialize(GsonDateTypeAdapter.java:34) 
at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) 
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) 
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) 
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) 
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
at com.google.gson.Gson.fromJson(Gson.java:803) 
at com.google.gson.Gson.fromJson(Gson.java:768) 
at com.google.gson.Gson.fromJson(Gson.java:717) 
at com.google.gson.Gson.fromJson(Gson.java:689) 
at com.arcbees.vcs.AbstractVcsApi.readEntity(AbstractVcsApi.java:86) 
at com.arcbees.vcs.AbstractVcsApi.processResponse(AbstractVcsApi.java:72) 
at com.arcbees.vcs.bitbucket.BitbucketApi.getOpenedPullRequests(BitbucketApi.java:74) 
at com.arcbees.pullrequest.PullRequestsTrigger.triggerBuild(PullRequestsTrigger.java:78) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java:1) 
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:84) 
... 7 more 
Caused by: java.lang.NumberFormatException: For input string: "2015-10-01T19:41:51.215215+00:00" 
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) 
at java.lang.Long.parseLong(Long.java:589) 
at java.lang.Long.parseLong(Long.java:631) 
at com.google.gson.JsonPrimitive.getAsLong(JsonPrimitive.java:238) 
at com.arcbees.vcs.util.GsonDateTypeAdapter.deserialize(GsonDateTypeAdapter.java:61) 
... 27 more

**Comment by meriouma** [comment]
Which version are you using? If you're not using the latest version, you can download it here. We did fix a few date related problems when Bitbucket changed it's date format. http://teamcity.arcbees.com/repository/download/TeamCityPlugins_CompileMaster/6469:id/pullrequests/target/pullrequests.zip

**Comment by joe-harter** [comment]
Thanks for the quick response. That is the version I upgraded to today (snapshot-20152508101432). We are on TeamCity 9.1.1

**Comment by meriouma** [comment]
Ok, thanks for confirming. I'll take a look ASAP

**Comment by joe-harter** [comment]
It just started working again with no intervention on our part.

**Comment by meriouma** [comment]
Weird. I'll close this issue for now. Please reopen it if the date format is wrong again
