### ISSUE TITLE
NumberFormatException when triggering a build with Pull Request

### ISSUE THREAD

**Issue by javfindly** [ArcBees/teamcity-plugins#32]
I'm not sure if there was a change in the Bitbucket API, but when the builds in TC are configured with Pull Request Triggers we are getting the next error on new pull request:

jetbrains.buildServer.buildTriggers.BuildTriggerException: java.lang.NumberFormatException: For input string: "2015-10-21T01:05:51.812812+00:00"
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:129)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$900(BuildTriggersChecker.java:127)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:11)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:55)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java:1)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:16)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:42)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.JsonParseException: java.lang.NumberFormatException: For input string: "2015-10-21T01:05:51.812812+00:00"
at com.arcbees.vcs.util.GsonDateTypeAdapter.deserialize(GsonDateTypeAdapter.java:63)
at com.arcbees.vcs.util.GsonDateTypeAdapter.deserialize(GsonDateTypeAdapter.java:34)
at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
at com.google.gson.Gson.fromJson(Gson.java:803)
at com.google.gson.Gson.fromJson(Gson.java:768)
at com.google.gson.Gson.fromJson(Gson.java:717)
at com.google.gson.Gson.fromJson(Gson.java:689)
at com.arcbees.vcs.AbstractVcsApi.readEntity(AbstractVcsApi.java:86)
at com.arcbees.vcs.AbstractVcsApi.processResponse(AbstractVcsApi.java:72)
at com.arcbees.vcs.bitbucket.BitbucketApi.getOpenedPullRequests(BitbucketApi.java:74)
at com.arcbees.pullrequest.PullRequestsTrigger.triggerBuild(PullRequestsTrigger.java:78)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java:1)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:98)
... 7 more
Caused by: java.lang.NumberFormatException: For input string: "2015-10-21T01:05:51.812812+00:00"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Long.parseLong(Long.java:441)
at java.lang.Long.parseLong(Long.java:483)
at com.google.gson.JsonPrimitive.getAsLong(JsonPrimitive.java:238)
at com.arcbees.vcs.util.GsonDateTypeAdapter.deserialize(GsonDateTypeAdapter.java:61)
... 27 more

Is there a new version required for this?

https://github.com/ArcBees/teamcity-plugins/blob/master/vcs-utils/src/main/java/com/arcbees/vcs/util/GsonDateTypeAdapter.java#L61

**Comment by meriouma** [comment]
Are you using the latest version? (http://teamcity.arcbees.com/viewLog.html?buildId=6469&tab=artifacts&buildTypeId=TeamCityPlugins_CompileMaster#!arnbv4v735s9)

**Comment by javfindly** [comment]
regexp doesn't match for "2015-10-21T01:05:51.812812+00:00", you are missing the '+' character. We will be writing a Pull Request to fix that

**Comment by meriouma** [comment]
My bad, this was fixed in https://github.com/ArcBees/teamcity-plugins/pull/30, but I forgot to merge it. New version should be compiling at the moment on teamcity

**Comment by javfindly** [comment]
great, could you let me know when is this going to be available?

**Comment by meriouma** [comment]
http://teamcity.arcbees.com/repository/download/TeamCityPlugins_CompileMaster/6784:id/pullrequests/target/pullrequests.zip

**Comment by javfindly** [comment]
deleting the Pull Request and creating it again also fixes the issue for whoever is reading. I'll close this issue, I've already tried with the date string and it works.
Thanks for your help
