### ISSUE TITLE
Exception Creating a new Pull Request Trigger

### ISSUE THREAD

**Issue by javfindly** [ArcBees/teamcity-plugins#35]
When creating new Pull Request for any project, I'm getting the next exception:

Trace: javax.el.PropertyNotFoundException: Property 'baseBranchKey' not found on type com.arcbees.vcs.VcsConstants
  at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:266)
  at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:243)
  at javax.el.BeanELResolver.property(BeanELResolver.java:353)
  at javax.el.BeanELResolver.getValue(BeanELResolver.java:97)
  at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:104)
  at org.apache.el.parser.AstValue.getValue(AstValue.java:183)
  at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
  at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:967)
  at org.apache.jsp.plugins.PullRequestTrigger.pullrequests_jsp._jspx_meth_props_005ftextProperty_005f4(pullrequests_jsp.java:545)
  at org.apache.jsp.plugins.PullRequestTrigger.pullrequests_jsp._jspService(pullrequests_jsp.java:218)
  at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
  at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
  at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
  at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
  at jetbrains.spring.web.TeamCityJSPServletImpl.access$001(TeamCityJSPServletImpl.java:11)
  at jetbrains.spring.web.TeamCityJSPServletImpl$1.apply(TeamCityJSPServletImpl.java:1)
  at jetbrains.buildServer.util.Util.doUnderContextClassLoader(Util.java:78)
  at jetbrains.spring.web.TeamCityJSPServletImpl.service(TeamCityJSPServletImpl.java:8)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
  at jetbrains.spring.web.JspController.doHandle(JspController.java:0)
  at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
  at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:154)
  at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
  at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:19)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
  at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)
  at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)
  at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:954)
  at org.apache.jsp.admin.triggers.showTriggerParams_jsp._jspx_meth_c_005fif_005f0(showTriggerParams_jsp.java:151)
  at org.apache.jsp.admin.triggers.showTriggerParams_jsp._jspService(showTriggerParams_jsp.java:99)
  at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
  at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
  at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
  at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
  at jetbrains.spring.web.TeamCityJSPServletImpl.access$001(TeamCityJSPServletImpl.java:11)
  at jetbrains.spring.web.TeamCityJSPServletImpl$1.apply(TeamCityJSPServletImpl.java:1)
  at jetbrains.buildServer.util.Util.doUnderContextClassLoader(Util.java:78)
  at jetbrains.spring.web.TeamCityJSPServletImpl.service(TeamCityJSPServletImpl.java:8)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
  at jetbrains.spring.web.JspController.doHandle(JspController.java:0)
  at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
  at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:154)
  at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
  at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:19)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
  at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
  at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
  at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
  at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:209)
  at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:267)
  at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1221)
  at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1005)
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:952)
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
  at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:19)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at jetbrains.buildServer.web.DependencyParametersCalculationContextFilter.doFilter(DependencyParametersCalculationContextFilter.java:3)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:8)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at jetbrains.buildServer.diagnostic.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:7)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:17)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.lang.Thread.run(Thread.java:745)

TeamCity Enterprise 9.0 (build 32060)
Pull Request Trigger	snapshot-20151702095528	ArcBees

**Comment by javfindly** [comment]
any news on this?

**Comment by javfindly** [comment]
I've tried with the latest version of the plugin, and I'm not getting this exception anymore. Thanks
