### ISSUE TITLE
bitbucket server url

### ISSUE THREAD

**Issue by mcmug8** [ArcBees/teamcity-plugins#38]
can you tell me what should I put in the server url section? We have bitbucket cloud setup. I am keep getting 400 or 404 when trying to input https://bitbucket.org or the repository https url as the server url

**Comment by meriouma** [comment]
I think there's a bug with the dropdown. Select GitHub, then switch back to Bitbucket. The dropdown should disappear

**Comment by mcmug8** [comment]
Thank you for your help. Now I am getting a bad request. Any idea how to fix this?


********************************************
Mar 18, 2016 10:01:06 AM com.arcbees.pullrequest.PullRequestStatusHandler handle
INFO: Handling build status - Build Status: STARTING, Branch: EN-9629-SidebarActivitiesView, isSuccessful: true
Mar 18, 2016 10:01:06 AM com.arcbees.pullrequest.PullRequestsBuildListener$2 run
SEVERE: Error updating pull request status.
com.arcbees.vcs.util.UnexpectedHttpStatusException: Failed to complete request. Status: HTTP/1.1 400 BAD REQUEST
{"error": {"fields": {"url": ["Enter a valid URL."]}, "message": "Bad request"}}
	at com.arcbees.vcs.AbstractVcsApi.doExecuteRequest(AbstractVcsApi.java:128)
	at com.arcbees.vcs.AbstractVcsApi.executeRequest(AbstractVcsApi.java:51)
	at com.arcbees.vcs.bitbucket.BitbucketApi.updateStatus(BitbucketApi.java:140)
	at com.arcbees.pullrequest.PullRequestStatusHandler.updateStatus(PullRequestStatusHandler.java:129)
	at com.arcbees.pullrequest.PullRequestStatusHandler.handle(PullRequestStatusHandler.java:85)
	at com.arcbees.pullrequest.PullRequestsBuildListener$2.run(PullRequestsBuildListener.java:87)
	at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Mar 18, 2016 10:01:26 AM com.arcbees.pullrequest.PullRequestStatusHandler handle
INFO: Handling build status - Build Status: STARTING, Branch: Build_fix_031816, isSuccessful: true

**Comment by meriouma** [comment]
Hmm, in the teamcity settings (Administration > Global Settings). Do you have a Server URL setup?

**Comment by mcmug8** [comment]
Yeah, it's set to http://buildserver:88  only internal can access. Could this be an issue?

**Comment by meriouma** [comment]
Shouldn't be. I'm just trying to figure out where that validation error is coming from

**Comment by mcmug8** [comment]
Yeah, do you think it's a bug in the code. Not sure why it's a bad request.

**Comment by mcmug8** [comment]
forgot to mention, it requires vpn connection first before the server url is accessible. Hope this helps.

**Comment by meriouma** [comment]
Looking at the code, the only way this could happen is if the server url isn't read correctly. Which version of TeamCity are you using?

**Comment by mcmug8** [comment]
thank you for you help meriouma! we figured out what was wrong here. looks like http://buildserver:88 is not a valid url. After changed the url to fully qualify http://buildserver.doman.net:88 and it works. don't know why.

**Comment by meriouma** [comment]
Glad you got it sorted out!
