### ISSUE TITLE
Repository Settings

### ISSUE THREAD

**Issue by dunkymole** [ArcBees/teamcity-plugins#39]
Hi,

Can I have some guidance around what should go in the 'Base branch' textbox in the Repository section of the settings? If I put 'master' a build is at least kicked off but fails with a null reference exception (below). Everything else I have tried results in nothing happening.

Thanks
Duncan

jetbrains.buildServer.buildTriggers.BuildTriggerException 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:91) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1100(BuildTriggersChecker.java:74) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:3)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:84) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java:1) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:9)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:37) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.NullPointerException 
at com.arcbees.pullrequest.PullRequestsTrigger.addBuildTask(PullRequestsTrigger.java:131) 
at com.arcbees.pullrequest.PullRequestsTrigger.triggerBuild(PullRequestsTrigger.java:105) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java:1) 
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:19) 
... 7 more

**Comment by meriouma** [comment]
Base branch should be your main development branch. You should also add `+:refs/heads/*` or something similar to your "Branch specification:" in the VCS settings.

Are you using a git repo?
