### ISSUE TITLE
jetbrains.buildServer.buildTriggers.BuildTriggerException with BB Server

### ISSUE THREAD

**Issue by Ashtonian** [ArcBees/teamcity-plugins#45]
Recently tried to setup the plugin with TC 9.1.7 and BB Server 4.4.2 and it returns this exception in TC. Not really sure where to go for further debugging?

`jetbrains.buildServer.buildTriggers.BuildTriggerException 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:44) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1100(BuildTriggersChecker.java:65) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:37)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:50) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:47)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:9) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.NullPointerException 
at com.arcbees.pullrequest.PullRequestsTrigger.addBuildTask(PullRequestsTrigger.java:131) 
at com.arcbees.pullrequest.PullRequestsTrigger.triggerBuild(PullRequestsTrigger.java:105) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java) 
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:32) 
... 7 more`

**Comment by Ashtonian** [comment]
[2016-05-18 15:17:50,058] console                           [Info] [2016-05-18 15:17:50,011]   WARN -   jetbrains.buildServer.SERVER - Pull Requests error in configuration projId:: projId {id=projId, internal id=bt6}: jetbrains.buildServer.buildTriggers.BuildTriggerException

**Comment by meriouma** [comment]
Hmm, we only tested it with bitbucket.org, maybe there are some different configurations? It seems to be related to the PR's latest commit hash

**Comment by meriouma** [comment]
This plugin only supports Bitbucket Cloud at the moment.

**Comment by yoramsh** [comment]
I was able to fix this issue, below is the patch in order to resolve this problem
 
--- a/vcs-utils/src/main/java/com/arcbees/vcs/stash/model/StashPullRequestTarget.java
+++ b/vcs-utils/src/main/java/com/arcbees/vcs/stash/model/StashPullRequestTarget.java
@@ -24,13 +24,13 @@ import com.arcbees.vcs.model.PullRequestTarget;
 public class StashPullRequestTarget implements PullRequestTarget<StashCommit, StashBranch> {
     private StashCommit commit;
     private StashBranch branch;
-    private String latestChangeset;
+    private String latestCommit;
     private String displayId;
 
     @Override
     public Commit getCommit() {
         if (commit == null) {
-            setCommit(new StashCommit(latestChangeset));
+            setCommit(new StashCommit(latestCommit));
         }
         return commit;
     }

**Comment by meriouma** [comment]
Thanks @yoramsh, I'll test your patch!

**Comment by yoram-s** [comment]
Hi @meriouma,
I've selected stush for the bb server.

**Comment by redhandpl** [comment]
Hi,

Is it implemented somewhere?

I'm facing this problem with TeamCity 2019.1.5 and BitBucket Server 6.9.1.
