### ISSUE TITLE
Broken API Call

### ISSUE THREAD

**Issue by nap** [ArcBees/teamcity-plugins#49]
I get the following error message in ```/opt/teamcity-9.1.7/logs/catalina.out``` for ```snapshot-20160508131018```
```
com.arcbees.vcs.util.UnexpectedHttpStatusException: Failed to complete request. Status: HTTP/1.1 404 Not Found
{"message":"null for uri: http://*****/rest/api/1.0/api/2.0/repositories/KEY/project_name/pullrequests/","status-code":404}
        at com.arcbees.vcs.AbstractVcsApi.doExecuteRequest(AbstractVcsApi.java:128)
        at com.arcbees.vcs.AbstractVcsApi.processResponse(AbstractVcsApi.java:63)
        at com.arcbees.vcs.bitbucket.BitbucketApi.getOpenedPullRequests(BitbucketApi.java:79)
        at com.arcbees.pullrequest.PullRequestsTrigger.triggerBuild(PullRequestsTrigger.java:83)
        at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java)
        at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
        at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:32)
        at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1100(BuildTriggersChecker.java:65)
        at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:37)
        at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:50)
        at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java)
        at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:47)
        at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:9)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by meriouma** [comment]
The plugin only support Bitbucket Cloud, are you using BB server?

**Comment by nap** [comment]
Yep, that would explain it.
Thanks.
