### ISSUE TITLE
Pull request builder throws exception

### ISSUE THREAD

**Issue by lucianomarisi** [ArcBees/teamcity-plugins#53]
The plugin looks great! 

However I'm unable to use it, currently I get the following exception both on team city 9 and 10.

```
[2016-10-11 17:55:23,257]   WARN - st.PullRequestsBuildListener$2 - Failed to execute PullRequest Handler. null 
java.lang.NullPointerException
    at com.arcbees.pullrequest.PullRequestStatusHandler.getPullRequestKey(PullRequestStatusHandler.java:205)
    at com.arcbees.pullrequest.PullRequestStatusHandler.getPullRequestBuild(PullRequestStatusHandler.java:186)
    at com.arcbees.pullrequest.PullRequestStatusHandler.handle(PullRequestStatusHandler.java:82)
    at com.arcbees.pullrequest.PullRequestsBuildListener$2.run(PullRequestsBuildListener.java:87)
    at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by meriouma** [comment]
Did you double check the user name/password and the owner/repository settings of the plugin?

**Comment by lucianomarisi** [comment]
@meriouma I did check the credentials at the time. I eventually went with the [Commit Status Publisher](https://confluence.jetbrains.com/display/TCD10/Commit+Status+Publisher) build feature with the same username/password.
