### ISSUE TITLE
'Approve' doesn't work after PullRequest build.

### ISSUE THREAD

**Issue by nirmalpathak** [ArcBees/teamcity-plugins#55]
Hi,

Please let me know the license associated with this plugin. Can it be used for commercial purpose on production servers?

We running TeamCity 9.1.7 (build 37573) on Windows OS. We are using your plugin to build pull request of Bitbucket. The PR trigger works fine however it fails to approve the PR.

We are getting following stack trace in logs.

Nov 29, 2016 3:07:07 PM com.arcbees.pullrequest.PullRequestsBuildListener$2 run
SEVERE: Error updating pull request status.
com.arcbees.vcs.util.UnexpectedHttpStatusException: Failed to complete request. Status: HTTP/1.1 400 BAD REQUEST
{"type": "error", "error": {"fields": {"url": ["Enter a valid URL."]}, "message": "Bad request"}}
 at com.arcbees.vcs.AbstractVcsApi.doExecuteRequest(AbstractVcsApi.java:128)
 at com.arcbees.vcs.AbstractVcsApi.executeRequest(AbstractVcsApi.java:51)
 at com.arcbees.vcs.bitbucket.BitbucketApi.updateStatus(BitbucketApi.java:140)
 at com.arcbees.pullrequest.PullRequestStatusHandler.updateStatus(PullRequestStatusHandler.java:129)
 at com.arcbees.pullrequest.PullRequestStatusHandler.handle(PullRequestStatusHandler.java:85)
 at com.arcbees.pullrequest.PullRequestsBuildListener$2.run(PullRequestsBuildListener.java:87)
 at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

Any idea how to fix this? Thanks.

**Comment by nirmalpathak** [comment]
I figured out the problem.

We didn't had FQDN setup on TeamCity server hence this was failing.
