### ISSUE TITLE
Illegal character in scheme name

### ISSUE THREAD

**Issue by Sandvich** [ArcBees/teamcity-plugins#57]
Full stacktrace (replacing our server url with <git_server>):

```
jetbrains.buildServer.buildTriggers.BuildTriggerException: Illegal character in scheme name at index 4: git1@<git_server>/rest/api/1.0/projects/builderbob@<git_server>/repos/dali/k8s/pull-requests/
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:123)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1200(BuildTriggersChecker.java:37)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:54)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$2.run(BuildTriggersChecker.java:2)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:74)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:113)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java:3)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:43)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:52)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 4: git1@vpt.co.uk:7990/rest/api/1.0/projects/builderbob@git1.vpt.co.uk:7990/repos/dali/k8s/pull-requests/
at java.net.URI.create(URI.java:852)
at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
at com.arcbees.vcs.stash.StashApi.getOpenedPullRequests(StashApi.java:76)
at com.arcbees.pullrequest.PullRequestsTrigger.triggerBuild(PullRequestsTrigger.java:83)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$5.run(BuildTriggersChecker.java:3)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:74)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:63)
... 9 more
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 4: git1@<git_server>/rest/api/1.0/projects/builderbob@<git_server>/repos/dali/k8s/pull-requests/
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.checkChars(URI.java:3021)
at java.net.URI$Parser.parse(URI.java:3048)
at java.net.URI.<init>(URI.java:588)
at java.net.URI.create(URI.java:850)
... 15 more
```

Any ideas what's causing this?

**Comment by meriouma** [comment]
The API URL should be set to the Stash URL, not the git repository

**Comment by Sandvich** [comment]
Thanks :)
