### ISSUE TITLE
Teamcity services issue while using PullRequest plugin

### ISSUE THREAD

**Issue by sandeep789** [ArcBees/teamcity-plugins#62]
Hi,
we are using teamcity 9.x version.
I have installed ArcBees Pullrequest plugin in my teamcity server, we are working this plugin from past 4 months, recently we face some issues in teamcity services. My teamcity services are stoped and starts again in 2 sec difference, we ask teamcity support taem about this issue, they said nothing  problem is from teamcity, you are using ArcBees Pullrequest plugin, check once that is the cause for issue or not. 
So please let me know why we are facing this issue. 
Please find below attached image.

Thanks,
Sandeep
![teamcityservices_issue](https://cloud.githubusercontent.com/assets/22836643/25380329/8607702c-29cd-11e7-876d-ab5825858ade.JPG)

**Comment by meriouma** [comment]
We are using the plugin with TC 9.x and have other users using the plugin and it's working fine.
Can you provide the mentioned logs? Maybe we'll identify something

**Comment by sandeep789** [comment]
Hi... Thank you for reply,
Here I am mentioned the logs,
[2017-04-06 02:49:14,052] console [Info] com.arcbees.vcs.util.UnexpectedHttpStatusException: Failed to complete request. Status: HTTP/1.1 429 Unknown Status Code
[2017-04-06 02:49:14,052] console [Info] Rate limit for this resource has been exceeded
[2017-04-06 02:49:14,052] console [Info] at com.arcbees.vcs.AbstractVcsApi.doExecuteRequest(AbstractVcsApi.java:128)
[2017-04-06 02:49:14,052] console [Info] at com.arcbees.vcs.AbstractVcsApi.processResponse(AbstractVcsApi.java:63)
[2017-04-06 02:49:14,052] console [Info] at com.arcbees.vcs.bitbucket.BitbucketApi.getOpenedPullRequests(BitbucketApi.java:79)
[2017-04-06 02:49:14,052] console [Info] at com.arcbees.pullrequest.PullRequestsTrigger.triggerBuild(PullRequestsTrigger.java:83)
[2017-04-06 02:49:14,052] console [Info] at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java)
[2017-04-06 02:49:14,052] console [Info] at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
[2017-04-06 02:49:14,052] console [Info] at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:32)
[2017-04-06 02:49:14,052] console [Info] at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1100(BuildTriggersChecker.java:65)
[2017-04-06 02:49:14,052] console [Info] at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:37)
[2017-04-06 02:49:14,052] console [Info] at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:50)
[2017-04-06 02:49:14,052] console [Info] at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java)
[2017-04-06 02:49:14,052] console [Info] at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:47)
[2017-04-06 02:49:14,052] console [Info] at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:9)
[2017-04-06 02:49:14,052] console [Info] at java.lang.Thread.run(Thread.java:745)
